language: cpp

compiler:
  - clang

notifications:
  email: false

env:
  - MPI=mpich2
  - MPI=mpich3
  - MPI=openmpi

install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo deb http://llvm.org/apt/precise/ llvm-toolchain-precise main | sudo tee -a /etc/apt/sources.list
  - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install -y clang-3.7 gcc-4.9 gfortran-4.9 libstdc++-4.9-dev cmake libopenblas-dev liblapack-dev
  - git pull --recurse-submodules
  - sh external/travis-install-mpi.sh $MPI

before_script:
  - export CC=clang-3.7
  - export CXX=clang++-3.7
  - sudo hostname localhost
  - test $MPI == mpich2 && MPIEXEC='mpiexec -launcher fork' || true
  - test $MPI == mpich3 && MPIEXEC='mpiexec -launcher fork' || true

script:
  - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=local ..
  - make -j8 -l8 && sudo make -j8 -l8 install && sudo ctest -j2 --output-on-failure
# - make -j8 -l8 all install && ctest -j2 --output-on-failure

