# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2015


notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\elemental

#environment:
#    MPI: mpich
#    F77: gfortran-5
#    PATH: /usr/lib/ccache/:$PATH

platform:
  - x86

# scripts that run after cloning repository
install:
  # Download MPI
  # Microsoft MPI
  - ps: "ci\\install-msmpi.ps1"
  - ps: "SetEnvMPI.cmd"
build:
        parallel: true                  # enable MSBuild parallel builds
build_script:
  - ps: "mkdir build"
  - ps: "cd build"
  - ps: "cmake -G \"Visual Studio 14 2015 Win64\" -DEL_TESTS=ON -DEL_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release .."  
  - ps: "make -j2"
test_script: 
  - ps: ctest --output-on-failure

cache:
      - C:\Downloads\MSMPI    -> ci\\install-msmpi.ps1    
